default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: piro_scrubber_development

test:
  <<: *default
  database: piro_scrubber_test<%=ENV['TEST_ENV_NUMBER']%>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
